{{ if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "submodel-server.fullname" . }}
  labels:
    {{- include "submodel-server.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- toYaml .Values.secret.data | nindent 2 }}
{{ end }}